/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrcamentosIndexRouteImport } from './routes/orcamentos.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as OrcamentosNovoRouteImport } from './routes/orcamentos.novo'
import { Route as OrcamentosIdRouteImport } from './routes/orcamentos.$id'
import { Route as ClientesNovoRouteImport } from './routes/clientes.novo'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosIndexRoute = OrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosNovoRoute = OrcamentosNovoRouteImport.update({
  id: '/orcamentos/novo',
  path: '/orcamentos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosIdRoute = OrcamentosIdRouteImport.update({
  id: '/orcamentos/$id',
  path: '/orcamentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/clientes/novo',
  path: '/clientes/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/clientes': typeof ClientesIndexRoute
  '/orcamentos': typeof OrcamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/clientes/': typeof ClientesIndexRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/clientes/'
    | '/orcamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/clientes'
    | '/orcamentos'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/clientes/$id'
    | '/clientes/novo'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/clientes/'
    | '/orcamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ClientesNovoRoute: typeof ClientesNovoRoute
  OrcamentosIdRoute: typeof OrcamentosIdRoute
  OrcamentosNovoRoute: typeof OrcamentosNovoRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  OrcamentosIndexRoute: typeof OrcamentosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/': {
      id: '/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof OrcamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/novo': {
      id: '/orcamentos/novo'
      path: '/orcamentos/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof OrcamentosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/$id': {
      id: '/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof OrcamentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/novo': {
      id: '/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ClientesIdRoute: ClientesIdRoute,
  ClientesNovoRoute: ClientesNovoRoute,
  OrcamentosIdRoute: OrcamentosIdRoute,
  OrcamentosNovoRoute: OrcamentosNovoRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  OrcamentosIndexRoute: OrcamentosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
