// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;
  // Treat obvious placeholder values as missing so the mock is used during local dev
  const isPlaceholder = (val?: string, marker?: string) => !val || val.includes('your-project') || val.includes('your-anon') || val.includes('your-anon-or-publishable-key');

  if (isPlaceholder(SUPABASE_URL, 'your-project') || isPlaceholder(SUPABASE_PUBLISHABLE_KEY, 'your-anon')) {
    if (import.meta.env.PROD) {
      throw new Error(
        'Supabase nao configurado: defina VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY no ambiente de producao.',
      );
    }
  }

  // If env vars are missing or set to the example placeholders, provide a lightweight mock Supabase client
  if (isPlaceholder(SUPABASE_URL, 'your-project') || isPlaceholder(SUPABASE_PUBLISHABLE_KEY, 'your-anon')) {
    // Minimal in-memory mocks to allow browsing the app without Supabase
    // default template (not tied to a specific user) — will be cloned per user on signup/signin
    const defaultStatusesTemplate = [
      { name: 'Pago', color: '#6366f1', sort_order: 0 },
      { name: 'Em aberto', color: '#3b82f6', sort_order: 1 },
      { name: 'Em produção', color: '#10b981', sort_order: 2 },
      { name: 'Fechado p/ pagamento', color: '#ef4444', sort_order: 3 },
    ];

    const mockDb: Record<string, any[]> = {
      products: [],
      profiles: [],
      clients: [],
      budgets: [],
      budget_items: [],
      budget_statuses: [],
      budget_status_assignments: [],
    };

    let currentSession: any = null;
    const authCallbacks: Array<(event: string, session: any) => void> = [];

    function makeUserId(email?: string) {
      if (!email) return `u_${Date.now()}`;
      return `u_${email.replace(/[^a-z0-9]/gi, '_').toLowerCase()}`;
    }

    function ensureDefaultStatusesForUser(userId: string) {
      const exists = (mockDb.budget_statuses || []).some((s) => s.user_id === userId);
      if (exists) return;
      mockDb.budget_statuses = mockDb.budget_statuses || [];
      defaultStatusesTemplate.forEach((t, idx) => {
        mockDb.budget_statuses.push({
          id: `${userId}_s${idx}_${Date.now()}`,
          user_id: userId,
          name: t.name,
          color: t.color,
          sort_order: t.sort_order,
          created_at: new Date().toISOString(),
        });
      });
    }

    const auth = {
      onAuthStateChange(cb: (event: string, session: any) => void) {
        authCallbacks.push(cb);
        return { subscription: { unsubscribe() { /* no-op */ } } };
      },
      async getSession() {
        return { data: { session: currentSession } };
      },
      async signOut() {
        currentSession = null;
        authCallbacks.forEach((cb) => cb('SIGNED_OUT', null));
        return { error: null };
      },
      async signIn({ email }: { email?: string } = {}) {
        // legacy alias
        return auth.signInWithPassword({ email, password: undefined });
      },
      async signInWithPassword({ email }: { email?: string; password?: string } = {}) {
        const id = makeUserId(email || 'local@example.com');
        const user = { id, email: email || 'local@example.com' };
        currentSession = { user };
        // ensure a lightweight profile exists
        mockDb.profiles = mockDb.profiles || [];
        const existingProfile = mockDb.profiles.find((p) => p.id === id || p.email === email);
        try { console.debug('[mock supabase] signInWithPassword for', email, 'resolved id', id, 'existingProfile:', existingProfile); } catch (e) {}
        if (!existingProfile) {
          mockDb.profiles.push({ id, email: email || 'local@example.com', name: '', company: '', phone: '' });
        }
        // ensure default statuses are available for this user
        ensureDefaultStatusesForUser(id);
        authCallbacks.forEach((cb) => cb('SIGNED_IN', currentSession));
        return { data: { session: currentSession }, error: null };
      },
      async signUp({ email, password, options }: { email?: string; password?: string; options?: any } = {}) {
        return auth.signUpWithOptions({ email, password, options });
      },
      async signUpWithOptions({ email, password, options }: { email?: string; password?: string; options?: any } = {}) {
        const id = makeUserId(email || `user_${Date.now()}`);
        const user = { id, email: email || 'local@example.com', ...options?.data };
        currentSession = { user };
        // persist profile
        mockDb.profiles = mockDb.profiles || [];
        const prof = { id, email: email || 'local@example.com', name: options?.data?.name || '', company: options?.data?.company || '', phone: options?.data?.phone || '' };
        mockDb.profiles.push(prof);
        try { console.debug('[mock supabase] signUpWithOptions created profile', prof); } catch (e) {}
        // clone default statuses for this new user
        ensureDefaultStatusesForUser(id);
        authCallbacks.forEach((cb) => cb('SIGNED_IN', currentSession));
        return { data: { user }, error: null };
      },
      async signUpWithOtp() {
        return { data: null, error: null };
      },
      async signUpWith() {
        return { data: null, error: null };
      },
      async signUpWithPassword({ email, password, options }: { email?: string; password?: string; options?: any } = {}) {
        return auth.signUpWithOptions({ email, password, options });
      }
    };

    function makeFrom(table: string) {
      // Simple chainable query builder supporting select, eq, order, maybeSingle, insert, upsert, delete, then
      const state: { selectCols?: string; filters: Array<{ col: string; val: any }>; orderBy?: string | null } = {
        selectCols: '*',
        filters: [],
        orderBy: null,
      };

      function applyFilters(arr: any[]) {
        let res = [...arr];
        for (const f of state.filters) {
          res = res.filter((item) => {
            // loose equality to match typical supabase behavior
            // support nested keys with dot notation if needed in future
            return item?.[f.col] == f.val;
          });
        }
        if (state.orderBy) {
          res.sort((a, b) => {
            const av = a?.[state.orderBy as string];
            const bv = b?.[state.orderBy as string];
            if (av == null) return -1;
            if (bv == null) return 1;
            if (av < bv) return -1;
            if (av > bv) return 1;
            return 0;
          });
        }
        return res;
      }

      const builder: any = {
        select(cols: string = '*') {
          state.selectCols = cols;
          return this;
        },
        eq(col: string, val: any) {
          state.filters.push({ col, val });
          return this;
        },
        order(col: string) {
          state.orderBy = col;
          return this;
        },
        maybeSingle() {
          const arr = applyFilters(mockDb[table] || []);
          const first = arr[0] ?? null;
          return Promise.resolve({ data: first, error: null });
        },
        insert: (row: any) => {
          const rows = Array.isArray(row) ? row : [row];
          const inserted = rows.map((entry, idx) => ({
            id: `${Date.now()}_${idx}`,
            created_at: new Date().toISOString(),
            ...entry,
          }));
          try { console.debug('[mock supabase] insert into', table, inserted); } catch (e) {}
          mockDb[table] = mockDb[table] || [];
          mockDb[table].push(...inserted);
          const result = { data: inserted, error: null };
          const insertBuilder: any = {
            select() {
              return this;
            },
            single() {
              return Promise.resolve({ data: inserted[0] ?? null, error: null });
            },
            maybeSingle() {
              return Promise.resolve({ data: inserted[0] ?? null, error: null });
            },
            then(cb?: any) {
              const resultPromise = Promise.resolve(result);
              if (typeof cb === 'function') return resultPromise.then(cb);
              return resultPromise;
            },
          };
          return insertBuilder;
        },
        upsert: async (row: any) => {
          try { console.debug('[mock supabase] upsert into', table, row); } catch (e) {}
          mockDb[table] = mockDb[table] || [];
          // simple replace by id if exists
          if (row && row.id) {
            const idx = mockDb[table].findIndex((r) => r.id == row.id);
            if (idx >= 0) mockDb[table][idx] = { ...mockDb[table][idx], ...row };
            else mockDb[table].push(row);
          } else {
            mockDb[table].push(row);
          }
          return { data: [row], error: null };
        },
        // delete() now supports .eq(col, val) pattern used by the app
        delete: () => {
          return {
            eq: (col: string, val: any) => {
              try { console.debug('[mock supabase] delete from', table, 'where', col, val); } catch (e) {}
              mockDb[table] = (mockDb[table] || []).filter((r) => r?.[col] != val);
              return Promise.resolve({ data: null, error: null });
            }
          };
        },
        then(cb?: any) {
          const arr = applyFilters(mockDb[table] || []);
          const resultPromise = Promise.resolve({ data: arr, error: null });
          if (typeof cb === 'function') return resultPromise.then(cb);
          return resultPromise;
        },
        update: (patch: any) => ({
          eq: (col: string, val: any) => {
            try { console.debug('[mock supabase] update', table, 'set', patch, 'where', col, val); } catch (e) {}
            mockDb[table] = (mockDb[table] || []).map((r) => (r?.[col] == val ? { ...r, ...patch } : r));
            const updated = (mockDb[table] || []).filter((r) => r?.[col] == val);
            return Promise.resolve({ data: updated, error: null });
          }
        }),
      };

      return builder;
    }

    const mockClient = {
      auth,
      from: (table: string) => makeFrom(table),
    } as unknown as ReturnType<typeof createSupabaseClient>;

    return mockClient;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
